custOrder:
	javac insertCustOrder.java
	java insertCustOrder
stored_in:
	javac insertStoredIn.java
	java insertStoredIn
offers:
	javac insertOffers.java
	java insertOffers
clean:
	rm insertCustOrder.class
	rm insertStoredIn.class

