compile:
	javac Payment.java
	javac Product.java
	javac cust_order.java
	javac Customer.java
	javac FreqShopper.java
	javac CustomerUI.java
	javac store_order.java
	javac StoreUI.java
	javac Store.java
	javac ManagerUI.java
	javac Manager.java
	javac Company.java
run:
	java Company
clean:
	rm Customer.class
	rm CustomerUI.class
	rm Company.class
	rm FreqShopper.class
